#!/usr/bin/env perl

use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec::Functions qw(catdir splitdir);
use Devel::REPL;

# Source directory has precedence
my @base = (splitdir(dirname(__FILE__)), '..');
my $lib = join('/', @base, 'lib');
-e catdir(@base, 't') ? unshift(@INC, $lib) : push(@INC, $lib);

# Start commands for application
require Mojolicious::Commands;


my $repl = Devel::REPL->new;
$repl->load_plugin($_) for qw(History LexEnv);
$repl->eval('
  use MojoRPC; 
  use Data::Dumper;
  my $app = MojoRPC->new();
  $app->startup();

');
$repl->run;