#!/usr/bin/env perl
use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec::Functions qw(catdir splitdir);

# Source directory has precedence
my @base = (splitdir(dirname(__FILE__)), '..');
my $lib = join('/', @base, 'lib');
-e catdir(@base, 't') ? unshift(@INC, $lib) : push(@INC, $lib);

use lib './lib';

# Start commands for application
require Mojolicious::Commands;

use MojoRPC::Server; 
use MojoRPC::Server::Whitelist;
use Data::Dumper;
my $app = MojoRPC::Server->new();
$app->startup();

my $whitelist = MojoRPC::Server::Whitelist->new();

print STDERR Dumper $whitelist->whitelist();